### ISSUE TITLE
future_watcher issue

### ISSUE THREAD

**Issue by dineshbvadhia** [belingud/rsgiadapter#1]
fastapi + starlette + granian + rsgiadapter. On windows 11. All latest versions.

The error is:
```
Traceback (most recent call last):
  File "...\Python311\Lib\site-packages\granian\_futures.py", line 4, in future_watcher
    await inner(watcher.scope, watcher.proto)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: FastAPI.__call__() missing 1 required positional argument: 'send'
```

**Comment by belingud** [comment]
Hi dineshbvadhia, thanks for your feedback and patient,

I'm unable to reproduce the issue, using example/_fastapi.py in Python3.11.9, on Windows 11.

Could you provide me with a minimal, executable code snippet?

**Comment by dineshbvadhia** [comment]
Found the problem. I was using `app` instead `rsgi_app`.

It says, "This project provides a way to run ASGI web frameworks on an RSGI server, but it is not recommended to use the RSGI server in this manner."

If it is not recommended then what is purpose of rsgiadapter?

**Comment by belingud** [comment]
> Found the problem. I was using `app` instead `rsgi_app`.
> 
> It says, "This project provides a way to run ASGI web frameworks on an RSGI server, but it is not recommended to use the RSGI server in this manner."
> 
> If it is not recommended then what is purpose of rsgiadapter?

Good question. Because it hasn't been performance tested or extensive tested.

Granian is the only one RSGI server for now, and it support ASGI protocol as well. So every one can deploy an ASGI work by granian with ASGI interface. I'm very optimistic about RSGI, hope it continues to make progress. It would be nice to see it incorporated into more open-source projects. I'd love to help more people become acquainted with it . So this is how this project begin. If things change in the future, I'll put more and more effort into making it better to accommodate new needs.

**Comment by dineshbvadhia** [comment]
Ok. I'll keep an eye on this repo for changes particulalrly for performance testing. Thanks :)
